app/index.ejs, nginx/default.conf, webpack.config.prod.js
Compress js with nginx and remove unneeded polyfill
=> Clean up for prod deploy

app/index.ejs
=> Babel Polyfill

app/js/components/events/EventModal.jsx, app/js/components/go/GoModal.jsx, app/js/components/mentoring/AddMentorForm.jsx, app/js/components/officers/OfficerForm.jsx, app/js/components/qdb/QDBModal.jsx, app/js/components/scoreboard/ViewMembershipsModal.jsx, app/js/containers/events/EventModal.js, app/js/containers/mentoring/AddMentorForm.js, app/js/containers/officers/OfficerForm.js, app/js/pages/Officers.jsx
@kristenmills Did I miss anything?
#67
=> Updated all form modals to work with default null

app/js/components/general/SmoothImageDiv.jsx, app/js/components/home/Hero.jsx, app/js/pages/Home.jsx, app/scss/home.scss
The SmoothImageDiv component will make sure a div background image is fully loaded before fully displaying it.
The SmoothImageDiv component takes an image url, className, and a delay in milliseconds.
The component will apply the "loading" class to the div until the background image has been loaded. The transition and "loading" properties will need to be set in your style sheet.
It also allows a delay to be specified to ensure different SmoothImageDivs will fade in at the same time.
The images on the homepage will set opacity to 0 until the images are loaded, with a delay of 400 ms.
Preview:
=> Created SmoothImageDiv general compnent, used on homepage hero.

.circleci/config.yml
=> Fixing the navbar

.circleci/config.yml
Cherry picked some build related commits for this. That way governing docs build
=> Hotfix build

app/js/components/officers/OfficerForm.jsx
This should fix @wadeanthony0100's problem.
=> Fixes rit-sse/node-api#49

app/js/components/general/Login.jsx, app/js/components/scoreboard/ViewMembershipsModal.jsx, app/js/pages/Events.jsx, app/js/pages/Go.jsx, app/js/pages/MembershipList.jsx, app/js/pages/Officers.jsx, app/js/pages/QDB.jsx, app/js/pages/Scoreboard.jsx
=> fixes for mobile responsiveness but it is kinda jank

app/js/components/officers/OfficerForm.jsx
=> Officer alias field

app/scss/nav.scss
=> Finally got around to fixing the nav when it goes mobile

app/js/components/officers/Officer.jsx
=> It's now 4 across instead of 3

app/js/actions/auth.js, app/js/actions/committees.js, app/js/actions/events.js, app/js/actions/go.js, app/js/actions/members.js, app/js/actions/officers.js, app/js/actions/quotes.js, app/js/actions/scroll.js, app/js/actions/tags.js, app/js/components/general/AsyncComponent.jsx, app/js/containers/events/EventList.js, app/js/containers/go/GoLinksList.js, app/js/containers/qdb/PendingQuoteList.js, app/js/containers/qdb/QuoteList.js, app/js/reducers/events.js, app/js/reducers/go.js, app/js/reducers/index.js, app/js/reducers/officers.js, app/js/reducers/quotes.js, app/js/reducers/scroll.js, app/js/store/status.js, package.json
updates to new api-client and makes errors log in dev
=> Pagination

app/js/pages/Home.jsx
Updated the home page to be grammatically correct for having multiple tutors in the SSE. -PS
=> Updated the home page 

app/js/components/home/Hero.jsx
This is changed in the Hero.jsx file
=> Changed the room number for the weekly meetings from 1520/1530 to 1670.

app/js/components/general/UserForm.jsx, app/js/components/scoreboard/AddMembershipModal.jsx
- Also, default start date to today
- Make some fields required to prevent incomplete submissions
Fixes #94 ?
=> Change Add Membership Datetime Fields to Date Fields

app/js/events/components/EventModal.jsx, app/js/go/components/GoLink.jsx, app/scss/actions.scss, app/scss/buttons.scss, app/scss/go.scss, app/scss/pane.scss, package-lock.json
Adds client-side validation to the events form, preventing incomplete submissions.
Also, add `cursor: pointer;` to buttons and make action buttons always visible for better UX.
Fixes #148
=> Events Form Validation

app/scss/member.scss
=> Add Visual Indication When Hovering Over Scoreboard Member

app/js/officers/components/Officer.jsx, app/scss/actions.scss
=> Make Some Actions Appear & Disappear On Hover

app/scss/actions.scss
=> Actually Make Some Actions Appear & Disappear On Hover

app/js/common/components/UserForm.jsx, app/js/events/components/EventModal.jsx
=> Small Fixes

package-lock.json, package.json
This adds package `cross-env` to facilitate development on Windows machines.
=> add cross-env to package.json scripts

app/js/common/components/List.jsx, app/js/common/components/LoginRequired.jsx, app/js/common/containers/Status.js, app/js/index.jsx, app/js/members/Page.jsx, app/js/members/actions.js, app/js/members/components/Profile.jsx, app/js/members/components/User.jsx, app/js/members/components/UsersTable.jsx, app/js/members/containers/Profile.js, app/js/members/containers/UserList.js, app/js/members/index.js, app/js/members/reducers.js, package-lock.json
Adds a page at `/members` which lists all users in the system sorted by DCE. Clicking on one of the rows in the table shows that member's profile page (`/members/:dce`) which lists their name, email, their officer role (if they're an officer), and when they were added to the system.
Related to #183
=> Add Members Page & Profiles

app/js/members/actions.js, app/js/members/components/Profile.jsx
Uses 'createdAt' on the first membership the user got instead of the user's 'createdAt' date.
Fixes #196 
Depends on rit-sse/node-api/pull/79
=> Fix "Member Since"

package-lock.json, package.json, webpack.config.prod.js
=> Update UglifyJSPlugin for Prod Webpack Builds

app/js/home/components/Hero.jsx, package.json
The meeting time needs to be updated.
Also, prepush hooks are garbage, I had to remove them to push code that was already on devlop.
=> Update meeting time

app/markdown/projects.md
Updated the projects page to include the new projects for the term. @cmb9400 can you approve/ look at these project descriptions before they are merged in? A lot of the projects also seemed to not have set meeting times yet, so I just put to check slack for each of them
=> Updating Projects Markdown file to reflect new projects

app/js/common/components/Layout.jsx, webpack.config.dev.js, webpack.config.prod.js
Adds shortened SHA for issue #213 so current version is displayed on footer of the website
=> Record SHA for issue #213

app/js/events/Page.jsx
Fixing issue https://github.com/rit-sse/OneRepoToRuleThemAll/issues/224
=> Change Link to a tag to download calendar.

app/markdown/about.md
Add donations information to about page.
=> Add donations link opening in new tab.

app/markdown/projects.md
Add BCI to the list of current projects
=> Add BCI to projects page

app/index.ejs, app/js/common/components/Actions.jsx, app/js/common/components/AsyncComponent.jsx, app/js/common/components/Login.jsx, app/js/common/components/Status.jsx, app/js/events/Page.jsx, app/js/qdb/components/PendingQuote.jsx, app/js/scoreboard/components/Member.jsx, app/markdown/projects.md
Scoreboard now shows medals rather than bars and projects page now has BCI added (was missing previously). 
Scoreboard update shown here:
Projects page update:
=> Updating score board medals as well as updating projects page for BCI

app/js/events/containers/EventList.js
If no events are present, events is an empty array. Trying to use the all object results in undefined hence the issue.
Fixes #165
=> Fixed #165 by checking if events are present

.gitignore, app/js/home/components/Hero.jsx
=> Update general meeting time

app/js/common/components/UserForm.jsx
The term has been outdated for a while and its confusing people so we're rewording it. Note this doesn't change the underlying model which still uses it
=> Reword dce on membership form

.gitmodules, README.md, app/markdown/governing-docs/constitution.md, app/markdown/governing-docs/primary-officers-policy.md
This should remove the submodule version and just add the files directly
=> Add governing docs to OneRepo

app/js/common/components/Actions.jsx, app/js/events/containers/EventList.js
Resolves filtering by committee on the events page
Updates the Actions (edit/delete) icons to use working font-awesome icons.
=> Fix filtering by committee on events page

app/js/home/Page.jsx, app/js/home/components/Hero.jsx, app/scss/home.scss
General meeting time was wrong and now theres also a link to the zoom and link to go/slides. Change requested by Lindsey.
=> Change general meeting info and add link to go/slides

app/js/home/components/Hero.jsx
We somehow missed this minor detail in the last code review.
=> Changed General Meeting URL to the right one

app/js/home/Page.jsx, app/js/home/components/Hero.jsx
I'm dumb and merged into devlop but forgot to merge that to master so here we finally go
=> Reflect accurate mentoring times on website

app/markdown/governing-docs/constitution.md
This amendment is drafted to be officially proposed and voted on in the Fall 2021 semester
=> Reverse the ranking for primary election voting to be more intuitive

app/js/home/components/Hero.jsx, app/markdown/governing-docs/constitution.md
Changes to the public site to accomidate recent schedule and officer information.
=> Merging updates to SSE website 
